name: Deploy Weather Pro

on:
  push:
    branches: [ main ] # Запуск при каждом сохранении кода
  workflow_dispatch:      # Ручной запуск

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Inject API Key
        run: |
          # Заменяем метку в HTML на реальный ключ из Secrets
          sed -i 's/REPLACE_WITH_API_KEY/${{ secrets.WEATHER_API_KEY }}/g' index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          
