name: Deploy Weather Pro

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # ОБЯЗАТЕЛЬНЫЙ БЛОК ПРАВ:
    permissions:
      contents: write
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Inject API Key
        run: |
          # Используем | как разделитель, на случай если в ключе есть косые черты
          sed -i 's|REPLACE_WITH_API_KEY|${{ secrets.WEATHER_API_KEY }}|g' index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
