name: Weather Radar Update

on:
  schedule:
    - cron: '0 * * * *' # Запуск каждый час
  workflow_dispatch:      # Возможность ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Tracker
        env:
          # Передаем секрет из настроек GitHub в переменную окружения системы
          MY_WEATHER_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: python tracker.py

      - name: Commit and Push
        run: |
          git config --global user.name "WeatherBot"
          git config --global user.email "bot@github.com"
          git add data/weather.json
          git commit -m "Update weather data: $(date)" || exit 0
          git push
          
